---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
output:
    html_document:
        fig_retina: 1
---

# 30 Day Chart Challenge 2026
## Day 07 - Distributions: Multiscale

### Load libraries & Set Themes
```{r}
#| label: Load libraries & Set Themes
pacman::p_load(
  tidyverse,
  janitor,
  ggrepel,
  ggtext,
  stringr,
  scales,
  MetBrewer,
  lubridate,
  ggh4x
  # showtext
)

# showtext and ggtext::element_markdown 
# are not behaving properly together
#
# font_add_google(
#   "Hanken Grotesk",
#   "Hanken Grotesk",
#   regular.wt = 400,
#   bold.wt = 800
# )
# showtext_auto()
# showtext_opts(dpi = 300)

warm_white <- "#f0ebe3ff"
warm_black <- "#38352fff"

# MetBrewer::MetPalettes$Nizami
colors_nizami <- c(
  orange_light = "#dd7867",
  red          = "#b83326", 
  orange_dark  = "#c8570d",
  yellow       = "#edb144",
  teal         = "#8cc8bc",
  teal_dark    = "#67a397",
  blue_light   = "#7da7ea",
  blue         = "#5773c0", 
  blue_dark    = "#1d4497"
)

theme_set(
  theme_minimal() +
    theme(
      # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
      # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
      # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(-0.15, "cm"),
      plot.background = element_rect(fill = warm_white),
      plot.title.position = "plot",
      plot.caption.position = "plot",
      plot.title = element_markdown(
        family = "Hanken Grotesk",
        size = 12,
        hjust = 0,
        lineheight = 1.2,
        margin = margin(0, 0, 15, 0),
      ),
      plot.caption = element_markdown(
        family = "Hanken Grotesk",
        size = 8,
        color = 'grey60',
        margin = margin(15, 0, 0, 0),
        hjust = 0,
        lineheight = 1.2
      ),
      plot.subtitle = element_markdown(
        size = 9,
        lineheight = 1.2,
        margin = margin(5, 0, 0, 0),
        hjust = 0.5
      ),
      axis.title.x = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.title.y = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.text = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40"
      ),
      legend.position = "top",
      text = element_text(family = "Hanken Grotesk", color = warm_black),
      plot.margin = margin(25, 25, 25, 25)
    )
)
```


### Read raw data
```{r}
raw_data <- 
  read_csv('2026/datasets/spotify_global_trends_2026 - spotify_global_trends_final.csv') |>
  janitor::clean_names()


```


### Preparing data for plot


```{r}
# data2plot <-
#   raw_data |>
#   group_by(occupation) |>
#   summarise(
#     stress_level = mean(stress_level),
#     daily_steps = mean(daily_steps)
#   ) |>
#   mutate(delta = (stress_level * 1000) - daily_steps)

data2plot <-
  raw_data |>
  filter(!str_detect(track_name, "Spider-Man")) |>
  slice_max(days, n = 10) |>
  mutate(
    label = track_name |>
      str_replace("\\(.*\\)", "") |>
      str_c(
        "<br>",
        "<span style='color:#aeaaa8ff'>",
        artist_name,
        '</span>'
      )
  ) |>
  select(label, days, streams)


```

### Time for plotting
```{r fig.showtext=TRUE}
my_plot <-
  data2plot |>
  mutate(label = fct_reorder(label, streams)) |>
  ggplot(aes(y = label)) +
  geom_col(
    aes(x = days),
    fill = "#bcb1a6ff"
  ) +
  theme(
    axis.text.y.left = element_markdown(
      family = "Hanken Grotesk",
      size = 8,
      lineheight = 0.9,
      color = "grey40"
    ),
    axis.text.x.top = element_markdown(
      family = "Hanken Grotesk",
      size = 8,
      lineheight = 0.9,
      color = colors_nizami[["orange_dark"]]
    ),
    axis.title.x.top = element_markdown(
      family = "Hanken Grotesk",
      size = 8,
      lineheight = 0.9,
      color = colors_nizami[["orange_dark"]]
    )
  ) +
  ggpattern::geom_col_pattern(
    pattern = 'stripe',
    aes(x = streams / 1000),
    pattern_color = colors_nizami[["orange_dark"]],
    fill = NA,
    pattern_spacing = 0.015,
    pattern_size = 0.1,
    pattern_angle = 45
  ) +
  scale_x_continuous(
    label = comma,
    expand = expansion(mult = c(0, 0)),
    sec.axis = sec_axis(trans = ~ . / 1000, name = "Streams (M)")
  ) +
  scale_y_discrete(expand = c(0, 0)) +
  labs(
    fill = NULL,
    y = NULL,
    x = "Days in Top 100",
    title = str_wrap(
      str_c(
        "**Enduring Hits** Do more days on the chart equal more streams?"
      ),
      width = 45,
      whitespace_only = FALSE
    ) |>
      str_replace_all("\n", "<br>"),
    caption = str_wrap(
      width = 65,
      'SOURCE Kaggle NOTE This visualization is a conceptual exercise focused on design and layout; it is intended as a stylistic study rather than a comprehensive or final analysis. GITHUB barreiro-r'
    ) |>
      str_replace_all("\n", "<br>")
  )
my_plot
ggsave(my_plot, width = 4, height = 5.5, filename = "2026/images/day07.png")
```