---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
output:
    html_document:
        fig_retina: 1
---

# 30 Day Chart Challenge 2026
## Day 06 - Comparisons: Reporters Without Borders Data Day

### Load libraries & Set Themes
```{r}
#| label: Load libraries & Set Themes
pacman::p_load(
  tidyverse,
  janitor,
  ggrepel,
  ggtext,
  stringr,
  scales,
  MetBrewer,
  lubridate,
  ggh4x,
  showtext
)

# showtext and ggtext::element_markdown 
# are not behaving properly together
#
# font_add_google(
#   "Hanken Grotesk",
#   "Hanken Grotesk",
#   regular.wt = 400,
#   bold.wt = 800
# )
# showtext_auto()
# showtext_opts(dpi = 300)

warm_white <- "#d0ccc5ff"
warm_black <- "#38352fff"

# MetBrewer::MetPalettes$Nizami
colors_nizami <- c(
  orange_light = "#dd7867",
  red          = "#b83326", 
  orange_dark  = "#c8570d",
  yellow       = "#edb144",
  teal         = "#8cc8bc",
  teal_dark    = "#67a397",
  blue_light   = "#7da7ea",
  blue         = "#5773c0", 
  blue_dark    = "#1d4497"
)

theme_set(
  theme_minimal() +
    theme(
      # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
      # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
      # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(-0.15, "cm"),
      plot.background = element_rect(fill = warm_white),
      plot.title.position = "plot",
      plot.caption.position = "plot",
      plot.title = element_markdown(
        family = "Hanken Grotesk",
        size = 12,
        hjust = 0,
        lineheight = 1.2,
        margin = margin(0, 0, 15, 0),
      ),
      plot.caption = element_markdown(
        family = "Hanken Grotesk",
        size = 8,
        color = 'grey60',
        margin = margin(15, 0, 0, 0),
        hjust = 0,
        lineheight = 1.2
      ),
      plot.subtitle = element_markdown(
        size = 9,
        lineheight = 1.2,
        margin = margin(5, 0, 0, 0),
        hjust = 0.5
      ),
      axis.title.x = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.title.y = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.text = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40"
      ),
      legend.position = "top",
      text = element_text(family = "Hanken Grotesk", color = warm_black),
      plot.margin = margin(25, 25, 25, 25)
    )
)
```


### Read raw data
```{r}
raw_data <- 
  read_delim('2026/datasets/rsf2025.csv', delim = ';') |>
  janitor::clean_names()
```


### Preparing data for plot


```{r}
data2plot <-
  raw_data |>
  mutate(score = rank_eco - rank_saf) |>
  select(country_en, rank_eco, rank_saf, score)

# slice top3 and bottom3
top3 <-
  bind_rows(
    data2plot |> slice_min(score, n = 3),
    data2plot |> slice_max(score, n = 3)
  )
```

### Time for plotting
```{r fig.showtext=TRUE}

my_plot <-
  data2plot |>
  ggplot(aes(x = rank_eco, y = rank_saf)) +
  annotate(
    "segment",
    x = -Inf,
    xend = Inf,
    y = -Inf,
    yend = Inf,
    color = 'grey60',
    linetype = 'dashed',
    linewidth = 0.6
  ) +
  geom_point(aes(color = abs(score))) +
  geom_text(data = top3, aes(label = country_en), size = 2.5, nudge_y = -4) +
  scale_color_gradientn(
    colors = MetBrewer::met.brewer('Nizami', direction = -1)
  ) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    legend.position = 'inside',
    legend.position.inside = c(1, 0),
    legend.justification = c(1, 0),
    legend.direction = 'horizontal'
  ) +
  guides(
    color = guide_colorbar(
      theme = theme(
        legend.key.width = unit(4, "lines"),
        legend.key.height = unit(0.2, "lines"),
        legend.title.position = 'top',
        legend.title = element_markdown(size = 8),
        legend.text = element_blank(),
        legend.ticks = element_blank()
      )
    )
  ) +
  labs(
    fill = NULL,
    color = "Higher<br>Discrepancy →",
    x = "Safety Rank",
    y = "Economy Rank",
    title = str_wrap(
      str_c(
        "**Reporters Without Borders** Comparison between safety and economy rankings"
      ),
      width = 45,
      whitespace_only = FALSE
    ) |>
      str_replace_all("\n", "<br>"),
    caption = str_wrap(
      width = 65,
      'SOURCE Kaggle NOTE This visualization is a conceptual exercise focused on design and layout; it is intended as a stylistic study rather than a comprehensive or final analysis. GITHUB barreiro-r'
    ) |>
      str_replace_all("\n", "<br>")
  )
my_plot
ggsave(my_plot, width = 4, height = 5.5, filename = "2026/images/day06.png")
```