---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
output:
    html_document:
        fig_retina: 1
---

# 30 Day Chart Challenge 2026
## Day 03 - Comparisons: Mosaic

### Load libraries & Set Themes
```{r}
#| label: Load libraries & Set Themes
pacman::p_load(
  tidyverse,
  janitor,
  ggrepel,
  ggtext,
  stringr,
  scales,
  MetBrewer,
  lubridate,
  ggh4x,
  showtext
)

# showtext and ggtext::element_markdown 
# are not behaving properly together
#
# font_add_google(
#   "Hanken Grotesk",
#   "Hanken Grotesk",
#   regular.wt = 400,
#   bold.wt = 800
# )
# showtext_auto()
# showtext_opts(dpi = 300)

font_add(family = "fa-solid", 
         regular = "Font Awesome 6 Free-Solid-900.otf")

warm_white <- "#f0ebe3ff"
warm_black <- "#38352fff"

# MetBrewer::MetPalettes$Nizami
colors_nizami <- c(
  orange_light = "#dd7867",
  red          = "#b83326", 
  orange_dark  = "#c8570d",
  yellow       = "#edb144",
  teal         = "#8cc8bc",
  teal_dark    = "#67a397",
  blue_light   = "#7da7ea",
  blue         = "#5773c0", 
  blue_dark    = "#1d4497"
)

theme_set(
  theme_minimal() +
    theme(
      # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
      # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
      # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(-0.15, "cm"),
      plot.background = element_rect(fill = warm_white),
      plot.title.position = "plot",
      plot.caption.position = "plot",
      plot.title = element_markdown(
        family = "Hanken Grotesk",
        size = 12,
        hjust = 0,
        lineheight = 1.2,
        margin = margin(0, 0, 15, 0),
      ),
      plot.caption = element_markdown(
        family = "Hanken Grotesk",
        size = 8,
        color = 'grey60',
        margin = margin(15, 0, 0, 0),
        hjust = 0,
        lineheight = 1.2
      ),
      plot.subtitle = element_markdown(
        size = 9,
        lineheight = 1.2,
        margin = margin(5, 0, 0, 0),
        hjust = 0.5
      ),
      axis.title.x = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.title.y = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.text = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40"
      ),
      legend.text = element_markdown(family = "Hanken Grotesk"),
      legend.position = "top",
      text = element_text(family = "Hanken Grotesk", color = warm_black),
      plot.margin = margin(25, 25, 25, 25)
    )
)
```


### Read raw data
```{r}
raw_data <- 
  read_csv('2026/datasets/spotify_global_trends_2026 - spotify_global_trends_final.csv')
```


### Preparing data for plot


```{r}
data2plot <-
  raw_data |>
  head(100) |>
  select(country, longevity) |>
  mutate(country = fct_lump(country, 4))

icon_labels <- c(
  `Stable Hit` = "\uf004",
  `New` = "\uf666",
  `Evergreen` = "\uf3a5"
)

full_names <-
  c(
    US = "United\nStates",
    KR = "South\nKorea",
    GB = "United\nKingdom",
    PR = "Puerto\nRico",
    Other = "Other"
  )

data2plot <-
  data2plot |>
  mutate(country_full = full_names[as.character(country)])

order <- data2plot |>
  count(country_full) |>
  filter(country_full != "Other") |>
  arrange(desc(n)) |>
  mutate(country_full = as.character(country_full)) |>
  pull(country_full) |>
  c("Other")
```

### Time for plotting
```{r fig.showtext=TRUE}
icons_title <- c(
  Stable_Hit = "<span style='font-family:\"Font Awesome 6 Free\"; font-weight:900;'><b>\uf004;</b></span>",
  New = "<span style='font-family:\"Font Awesome 6 Free\"; font-weight:900;'><b>\uf666;</b></span>",
  Evergreen = "<span style='font-family:\"Font Awesome 6 Free\"; font-weight:900;'><b>\uf3a5;</b></span>"
)

devtools::install_github("haleyjeppson/ggmosaic")
pacman::p_load(ggmosaic)


my_plot <-
  data2plot |>
  mutate(country_full = fct_relevel(country_full, rev(order))) |>
  ggplot() +
  geom_mosaic(
    aes(x = product(country_full), fill = longevity),
    show.legend = FALSE
  ) +
  scale_fill_manual(
    values = c(
      "Stable Hit" = colors_nizami[["blue"]],
      "New" = colors_nizami[["orange_dark"]],
      "Evergreen" = colors_nizami[["teal"]]
    )
  ) +
  coord_flip(expand = FALSE) +
  labs(
    fill = NULL,
    title = str_wrap(
      str_c(
        "**The land of the Hits** A proportional breakdown of song performance categories across top regions of Spotify Top 100 songs."
      ),
      width = 42,
      whitespace_only = FALSE
    ) |>
      str_c("<span style='font-size:12px'>") |>
      str_c(
        "\n\n<span style='color:",
        colors_nizami[["blue"]],
        "'>",
        icons_title[["Stable_Hit"]],
        " Stable Hit</span> consistently performing over time;"
      ) |>
      str_c(
        "\n<span style='color:",
        colors_nizami[["orange_dark"]],
        "'>",
        icons_title[["New"]],
        " New</span> recently entered the chart;"
      ) |>
      str_c(
        "\n<span style='color:",
        colors_nizami[["teal_dark"]],
        "'>",
        icons_title[["Evergreen"]],
        " Evergreen</span> long-term sustained success;"
      ) |>
      str_replace_all("\n", "<br>"),
    caption = str_wrap(
      width = 65,
      'SOURCE Kaggle NOTE This visualization is a conceptual exercise focused on design and layout; it is intended as a stylistic study rather than a comprehensive or final analysis. GITHUB barreiro-r'
    ) |>
      str_replace_all("\n", "<br>")
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )

ggsave(my_plot, width = 4, height = 5.5, filename = "2026/images/day03.png")
```
