---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
output:
    html_document:
        fig_retina: 1
---

# 30 Day Chart Challenge 2026
## Day 05 - Comparisons: Experimental

### Load libraries & Set Themes
```{r}
#| label: Load libraries & Set Themes
pacman::p_load(
  tidyverse,
  janitor,
  ggrepel,
  ggtext,
  stringr,
  scales,
  MetBrewer,
  lubridate,
  ggh4x,
  showtext
)

# showtext and ggtext::element_markdown 
# are not behaving properly together
#
# font_add_google(
#   "Hanken Grotesk",
#   "Hanken Grotesk",
#   regular.wt = 400,
#   bold.wt = 800
# )
# showtext_auto()
# showtext_opts(dpi = 300)

font_add(family = "fa-solid", 
         regular = "Font Awesome 6 Free-Solid-900.otf")

warm_white <- "#f0ebe3ff"
warm_black <- "#38352fff"

# MetBrewer::MetPalettes$Nizami
colors_nizami <- c(
  orange_light = "#dd7867",
  red          = "#b83326", 
  orange_dark  = "#c8570d",
  yellow       = "#edb144",
  teal         = "#8cc8bc",
  teal_dark    = "#67a397",
  blue_light   = "#7da7ea",
  blue         = "#5773c0", 
  blue_dark    = "#1d4497"
)

theme_set(
  theme_minimal() +
    theme(
      # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
      # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
      # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(-0.15, "cm"),
      plot.background = element_rect(fill = warm_white),
      plot.title.position = "plot",
      plot.caption.position = "plot",
      plot.title = element_markdown(
        family = "Hanken Grotesk",
        size = 12,
        hjust = 0,
        lineheight = 1.2,
        margin = margin(0, 0, 15, 0),
      ),
      plot.caption = element_markdown(
        family = "Hanken Grotesk",
        size = 8,
        color = 'grey60',
        margin = margin(15, 0, 0, 0),
        hjust = 0,
        lineheight = 1.2
      ),
      plot.subtitle = element_markdown(
        size = 9,
        lineheight = 1.2,
        margin = margin(5, 0, 0, 0),
        hjust = 0.5
      ),
      axis.title.x = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.title.y = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.text = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40"
      ),
      legend.text = element_markdown(family = "Hanken Grotesk"),
      legend.position = "top",
      text = element_text(family = "Hanken Grotesk", color = warm_black),
      plot.margin = margin(25, 25, 25, 25)
    )
)
```


### Read raw data
```{r}
raw_data <- 
  read_csv('2026/datasets/spotify_global_trends_2026 - spotify_global_trends_final.csv')
```


### Preparing data for plot


```{r}
data2plot <-
  raw_data |>
  filter(genre != "Billboard Hot 100") |>
  mutate(genre_lump = fct_lump(tolower(genre), w = streams, n = 5))

# Collect Popular Genres
main_genres <-
  data2plot |>
  distinct(genre_lump) |>
  pull(genre_lump)

search_expression <-
  main_genres |>
  str_c(collapse = "|") |>
  tolower()

# Trying to reduce the number of Other
reclassifying_genres <-
  data2plot |>
  filter(genre != "Billboard Hot 100") |>
  distinct(genre) |>
  mutate(
    extracted_word = str_extract(tolower(genre), search_expression),
    main_genre = coalesce(extracted_word, search_expression)
  ) |>
  select(-main_genre)

data2plot <-
  data2plot |>
  left_join(reclassifying_genres, by = "genre") |>
  mutate(
    genre_lump = if_else(
      genre_lump == "Other" & !is.na(extracted_word),
      extracted_word,
      genre_lump
    )
  ) |>
  mutate(genre_lump = str_to_title(genre_lump))

better_levels <-
  data2plot |>
  mutate(genre_lump = as.character(genre_lump)) |>
  group_by(genre_lump) |>
  summarise(sum_streams = sum(streams)) |>
  arrange(desc(sum_streams)) |>
  filter(genre_lump != "Other") |>
  pull(genre_lump) |>
  c("Other")

data2plot <-
  data2plot |>
  mutate(
    genre_lump = factor(
      genre_lump,
      levels = better_levels
    )
  )
```

### Time for plotting
```{r fig.showtext=TRUE}
pacman::p_load("ggpattern")
new_order <-
  data2plot |>
  arrange(desc(genre_lump), streams) |>
  pull(track_name)

my_plot <-
  data2plot |>
  ggplot(aes(y = streams, x = track_name)) +
  geom_col(
    data = data2plot |> mutate(streams = max(streams)),
    fill = grid::linearGradient(c("#7d60a2ff", "#f7f0f8ff")),
    color = NULL,
    width = 1.3
  ) +
  geom_col(
    data = data2plot |> mutate(streams = 3 * -10^6),
    fill = "#ffffffff",
    width = 1.3
  ) +
  annotate(
    "segment",
    x = -Inf,
    xend = Inf,
    y = 3 * -10^6,
    color = warm_black,
    linewidth = 0.2
  ) +
  annotate(
    "segment",
    x = -Inf,
    xend = Inf,
    y = data2plot$streams |> max(),
    color = warm_black,
    linewidth = 0.2
  ) +
  geom_col(
    aes(fill = genre_lump),
    width = 1.1,
    alpha = 0.8,
    key_glyph = "point"
  ) +
  scale_x_discrete(limits = new_order) +
  theme(
    axis.text.y = element_blank()
  ) +
  coord_radial(expand = FALSE, inner.radius = 0.2) +
  MetBrewer::scale_fill_met_d("Renoir") +
  theme(
    axis.text.y = element_blank(),
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  ) +
  guides(
    fill = guide_legend(
      override.aes = list(
        shape = 21, # Shape 21 is a circle that takes a 'fill' aesthetic
        size = 4, # Make the dot larger and easier to see
        color = NA # (Optional) Removes the black border around the dot
      )
    )
  ) +
  labs(
    fill = NULL,
    title = str_wrap(
      str_c(
        "**Spinning the Hits** Total stream counts by genre for the 2026 Spotify Top 100"
      ),
      width = 35,
      whitespace_only = FALSE
    ) |> str_replace_all("\n", "<br>"),
    caption = str_wrap(
      width = 60,
      'SOURCE Kaggle NOTE This visualization is a conceptual exercise focused on design and layout; it is intended as a stylistic study rather than a comprehensive or final analysis. GITHUB barreiro-r'
    ) |>
      str_replace_all("\n", "<br>")
  )

ggsave(my_plot, width = 4, height = 5.5, filename = "2026/images/day05.png")
```