---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
output:
    html_document:
        fig_retina: 1
---

# 30 Day Chart Challenge 2026
## Day 14 - Relationship: Trade

Reference: https://flowingdata.com/2026/03/23/cities-with-most-ice-arrests/

### Load libraries & Set Themes
```{r}
#| label: Load libraries & Set Themes
pacman::p_load(
  tidyverse,
  janitor,
  ggrepel,
  ggtext,
  stringr,
  scales,
  MetBrewer,
  lubridate,
  ggh4x
  # showtext
)

# showtext and ggtext::element_markdown 
# are not behaving properly together
#
# font_add_google(
#   "Hanken Grotesk",
#   "Hanken Grotesk",
#   regular.wt = 400,
#   bold.wt = 800
# )
# showtext_auto()
# showtext_opts(dpi = 300)

warm_white <- "#f0ebe3ff"
warm_black <- "#38352fff"

# MetBrewer::MetPalettes$Nizami
colors_nizami <- c(
  orange_light = "#dd7867",
  red          = "#b83326", 
  orange_dark  = "#c8570d",
  yellow       = "#edb144",
  teal         = "#8cc8bc",
  teal_dark    = "#67a397",
  blue_light   = "#7da7ea",
  blue         = "#5773c0", 
  blue_dark    = "#1d4497"
)

theme_set(
  theme_minimal() +
    theme(
      # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
      # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
      # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(-0.15, "cm"),
      plot.background = element_rect(fill = warm_white),
      plot.title.position = "plot",
      plot.caption.position = "plot",
      plot.title = element_markdown(
        family = "Hanken Grotesk",
        size = 12,
        hjust = 0,
        lineheight = 1.2,
        margin = margin(0, 0, 15, 0),
      ),
      plot.caption = element_markdown(
        family = "Hanken Grotesk",
        size = 8,
        color = 'grey60',
        margin = margin(15, 0, 0, 0),
        hjust = 0,
        lineheight = 1.2
      ),
      plot.subtitle = element_markdown(
        size = 9,
        lineheight = 1.2,
        margin = margin(5, 0, 0, 0),
        hjust = 0.5
      ),
      axis.title.x = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.title.y = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.text = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40"
      ),
      legend.position = "top",
      text = element_text(family = "Hanken Grotesk", color = warm_black),
      plot.margin = margin(25, 25, 25, 25)
    )
)
```


### Read raw data
```{r}
pacman::p_load(tidyquant)
library(tidyquant)

# 1. Fetch Netflix (NFLX) data and convert it to monthly
netflix_monthly <- tq_get("NFLX", from = "2010-01-01") |>
  mutate(period_4m = floor_date(date, "4 months")) |>
  group_by(period_4m) |>
  summarise(
    open = first(open),
    close = last(close),
    high = max(high),
    low = min(low),
    volume = sum(volume))
```


### Preparing data for plot
```{r}
callout <- str_c(
  sep = "<br>",
  "**Losses subscribers for the first time**",
  str_wrap(
    "in the Q1 Netflix annouced the loss of 200,000 subscribers and forecasted 2M subscribers loss in Q2. Investors panicked.",
    width = 40
  ) |>
    str_replace_all("\n", "<br>")
)

my_plot <-
  netflix_monthly |>
  ggplot(aes(x = period_4m)) +
  geom_segment(
    aes(y = high, yend = low, color = open < close),
    size = 0.5,
    show.legend = FALSE
  ) +
  geom_segment(
    aes(y = open, yend = close, color = open < close),
    size = 2,
    show.legend = FALSE
  ) +
  geom_richtext(
    aes(x = date("2008-09-01"), y = 95, label = callout),
    stat = "unique",
    size = 3,
    lineheight = 1.2,
    color = warm_black,
    hjust = 0,
    vjust = 1.03,
    fill = NA,
    label.color = NA
  ) +
  annotate(
    geom = "curve",
    x = date("2021-09-01"),
    xend = date("2015-09-01"),
    y = 45,
    yend = 60,
    curvature = -0.3,
    angle = 60,
    color = warm_black,
    linewidth = 0.4,
    arrow = arrow(type = "closed", length = unit(0.05, "inches"))
  ) +
  scale_color_manual(
    values = c(
      "TRUE" = colors_nizami[["teal"]],
      "FALSE" = colors_nizami[["orange_light"]]
    )
  ) +
  theme(panel.grid.major.y = element_line(color = "grey80", linewidth = .3)) +
  labs(
    fill = NULL,
    y = NULL,
    x = NULL,
    title = str_wrap(
      str_c(
        "**Netflix Stocks** in 2022 NFLX stock price dropped by over 60% of its value"
      ),
      width = 45,
      whitespace_only = FALSE
    ) |>
      str_c(
        "<br><br><span style='font-size:12px'>Share Price (USD)</span>"
      ) |>
      str_replace_all("\n", "<br>"),
    caption = str_wrap(
      width = 65,
      'SOURCE {tidyquant} NOTE This visualization is a conceptual exercise focused on design and layout; it is intended as a stylistic study rather than a comprehensive or final analysis. GITHUB barreiro-r'
    ) |>
      str_replace_all("\n", "<br>")
  )
my_plot
ggsave(my_plot, width = 4, height = 5.5, filename = "2026/images/day14.png")
```