---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
output:
    html_document:
        fig_retina: 1
---

# 30 Day Chart Challenge 2026
## Day 18 - Relationship: UNICEF (dataday)

### Load libraries & Set Themes
```{r}
#| label: Load libraries & Set Themes
pacman::p_load(
  tidyverse,
  janitor,
  ggrepel,
  ggtext,
  stringr,
  scales,
  MetBrewer,
  lubridate,
  ggh4x
  # showtext
)

# showtext and ggtext::element_markdown 
# are not behaving properly together
#
# font_add_google(
#   "Hanken Grotesk",
#   "Hanken Grotesk",
#   regular.wt = 400,
#   bold.wt = 800
# )
# showtext_auto()
# showtext_opts(dpi = 300)

warm_white <- "#f0ebe3ff"
warm_black <- "#38352fff"

# MetBrewer::MetPalettes$Nizami
colors_nizami <- c(
  orange_light = "#dd7867",
  red          = "#b83326", 
  orange_dark  = "#c8570d",
  yellow       = "#edb144",
  teal         = "#8cc8bc",
  teal_dark    = "#67a397",
  blue_light   = "#7da7ea",
  blue         = "#5773c0", 
  blue_dark    = "#1d4497"
)

theme_set(
  theme_minimal() +
    theme(
      # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
      # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
      # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(-0.15, "cm"),
      plot.background = element_rect(fill = warm_white),
    #   plot.title.position = "plot",
    #   plot.caption.position = "plot",
      plot.title = element_markdown(
        family = "Hanken Grotesk",
        size = 12,
        hjust = 0,
        lineheight = 1.2,
        margin = margin(0, 0, 15, 0),
      ),
      plot.caption = element_markdown(
        family = "Hanken Grotesk",
        size = 8,
        color = 'grey60',
        margin = margin(15, 0, 0, 0),
        hjust = 0,
        lineheight = 1.2
      ),
      plot.subtitle = element_markdown(
        size = 9,
        lineheight = 1.2,
        margin = margin(5, 0, 0, 0),
        hjust = 0.5
      ),
      axis.title.x = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.title.y = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.text = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40"
      ),
      legend.position = "top",
      text = element_text(family = "Hanken Grotesk", color = warm_black),
      plot.margin = margin(25, 25, 25, 25)
    )
)
```


### Read raw data

Original: https://data.unicef.org/resources/dataset/nutrition-school-children-adolescents/
```{r}
# Loading data
pacman::p_load(readxl)

header <-
  read_excel(
    "2026/datasets/UNICEF_Global-database_SACA_obesity_August-2025-V2.xlsx",
    sheet = "5to9",
    skip = 6,
    range = "B7:EN9",
    col_names = FALSE
  ) |>
  t() |>
  as.tibble(stringsAsFactors = FALSE) |>
  fill(V1, V2, .direction = "down") |>
  transmute(
    combined_name = paste(V1, V2, V3, sep = "-") |> str_remove_all("-NA")
  ) |>
  pull(combined_name)

raw_data <-
  read_excel(
    "2026/datasets/UNICEF_Global-database_SACA_obesity_August-2025-V2.xlsx",
    sheet = "5to9",
    skip = 10,
    col_names = FALSE
  ) |>
  set_names(header) |>
  pivot_longer(
    cols = starts_with('2'),
    names_to = 'name',
    values_to = 'value'
  ) |>
  mutate(name = str_remove(name, 'x')) |>
  separate(
    name,
    into = c('year', 'sex', 'estimator'),
    sep = '-',
    convert = TRUE
  ) |>
  janitor::clean_names() |>
  mutate(
    estimator = snakecase::to_snake_case(estimator),
    sex = snakecase::to_snake_case(sex)
  ) 
```


### Preparing data for plot
```{r}
data2plot <-
  raw_data |>
  filter(estimator == 'point_estimate') |>
  filter(sex %in% c('females', 'males')) |>
  filter(world_bank_income_groups != "Not Classified") |>
  mutate(
    world_bank_income_groups = factor(
      world_bank_income_groups,
      levels = c(
        "High Income",
        "Upper Middle Income",
        "Lower Middle Income",
        "Low Income"
      )
    )
  ) |>
group_by(world_bank_income_groups, year, sex, estimator) |>
  summarise(value = mean(as.numeric(value), na.rm = TRUE), .groups = "drop")
```


### Time for plotting
```{r fig.showtext=TRUE}
pacman::p_load(patchwork)

my_plot <-
  data2plot |>
  ggplot(aes(x = year, y = value, color = world_bank_income_groups)) +
  geom_line(
    aes(
      group = interaction(world_bank_income_groups, sex),
      color = sex,
      alpha = world_bank_income_groups,
    ),
    show.legend = FALSE
  ) +
  geom_point(color = warm_white, size = 1) +
  geom_point(
    aes(color = sex, alpha = world_bank_income_groups),
    size = 1,
    shape = 21
  ) +
  scale_alpha_manual(
    values = rev(c(0.25, 0.5, 0.75, 1)),
    label = ~ . |> str_remove(" Income")
  ) +
  scale_color_manual(
    values = c(
      "females" = colors_nizami[["red"]],
      "males" = colors_nizami[["blue"]]
    )
  ) +
  scale_y_continuous(labels = function(x) scales::percent(x / 100)) +
  facet_wrap(~sex) +
  theme(
    panel.grid.major.y = element_line(color = 'grey80', linewidth = .3),
    strip.text = element_markdown(
      hjust = 0,
      size = 12,
      color = warm_black,
      margin = margin(0, 0, 0, 0)
    ),
    legend.justification = "left",
    legend.margin = margin(0, 0, 0, 0),
    legend.box.margin = margin(0, 0, 0, 0),
    legend.spacing = unit(0, "cm"),
    legend.key.spacing   = unit(0.1, "cm"),
    legend.key.width     = unit(0, "cm"),
  ) +
  labs(
    alpha = "Income",
    x = NULL,
    y = NULL,
    fill = NULL,
    title = str_wrap(
      str_c(
        "**UNICEF's Global database on school-age children and adolescents' nutrition** Childs from 5 to 9 years of age, last updated in 2025"
      ),
      width = 45,
      whitespace_only = FALSE
    ) |>
      glue::glue(
        "<br><br><span style='font-size:12px'>% of child with obesity</span>"
      ) |>
      str_replace_all("\n", "<br>"),
    caption = str_wrap(
      width = 65,
      'SOURCE Bureau of Economic Analysis / TidyTuesday NOTE This visualization is a conceptual exercise focused on design and layout; it is intended as a stylistic study rather than a comprehensive or final analysis. GITHUB barreiro-r'
    ) |>
      str_replace_all("\n", "<br>"),
  ) +
  guides(
    color = "none",
    alpha = guide_legend(
      position = "bottom",
      override.aes = list(shape = 16),
    )
  )

ggsave(
  my_plot,
  width = 4,
  height = 5.5,
  filename = "2026/images/day18.png"
)
```