---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
output:
    html_document:
        fig_retina: 1
---

# 30 Day Chart Challenge 2026
## Day 19 - Timeseries: Evolution

### Load libraries & Set Themes
```{r}
#| label: Load libraries & Set Themes
pacman::p_load(
  tidyverse,
  janitor,
  ggrepel,
  ggtext,
  stringr,
  scales,
  MetBrewer,
  lubridate,
  ggh4x
  # showtext
)

# showtext and ggtext::element_markdown 
# are not behaving properly together
#
# font_add_google(
#   "Hanken Grotesk",
#   "Hanken Grotesk",
#   regular.wt = 400,
#   bold.wt = 800
# )
# showtext_auto()
# showtext_opts(dpi = 300)

warm_white <- "#f0ebe3ff"
warm_black <- "#38352fff"

# MetBrewer::MetPalettes$Nizami
colors_nizami <- c(
  orange_light = "#dd7867",
  red          = "#b83326", 
  orange_dark  = "#c8570d",
  yellow       = "#edb144",
  teal         = "#8cc8bc",
  teal_dark    = "#67a397",
  blue_light   = "#7da7ea",
  blue         = "#5773c0", 
  blue_dark    = "#1d4497"
)

theme_set(
  theme_minimal() +
    theme(
      # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
      # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
      # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(-0.15, "cm"),
      plot.background = element_rect(fill = warm_white),
      plot.title.position = "plot",
      plot.caption.position = "plot",
      plot.title = element_markdown(
        family = "Hanken Grotesk",
        size = 12,
        hjust = 0,
        lineheight = 1.2,
        margin = margin(0, 0, 15, 0),
      ),
      plot.caption = element_markdown(
        family = "Hanken Grotesk",
        size = 8,
        color = 'grey60',
        margin = margin(15, 0, 0, 0),
        hjust = 0,
        lineheight = 1.2
      ),
      plot.subtitle = element_markdown(
        size = 9,
        lineheight = 1.2,
        margin = margin(5, 0, 0, 0),
        hjust = 0.5
      ),
      axis.title.x = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.title.y = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.text = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40"
      ),
      legend.position = "top",
      text = element_text(family = "Hanken Grotesk", color = warm_black),
      plot.margin = margin(25, 25, 25, 25)
    )
)
```


### Read raw data

Original: https://data.unicef.org/resources/dataset/nutrition-school-children-adolescents/
```{r}
# Loading data
raw_data <- tidytuesdayR::tt_load('2025-08-26')
```


### Preparing data for plot
```{r}
top_lyrical_topic <-
  raw_data$billboard |>
  separate_rows(lyrical_topic, sep = ";") |>
  count(lyrical_topic) |>
  filter(!is.na(lyrical_topic)) |>
  slice_max(n, n = 9) |>
  pull(lyrical_topic) |>
  unique()


data2plot <-
  raw_data$billboard |>
  mutate(year = year(date)) |>
  select(lyrical_topic, year) |>
  separate_rows(lyrical_topic, sep = ";") |>
  mutate(lyrical_topic = fct_lump(lyrical_topic, 9)) |>
  filter(!is.na(lyrical_topic))
```


### Time for plotting
```{r fig.showtext=TRUE}
# df_midpoints <-
#   data2plot |>
#   group_by(lyrical_topic) |>
#   summarise(count = n()) |>
#   ungroup() |>
#   mutate(percentage = count / sum(count)) |>
#   arrange(desc(lyrical_topic)) |>
#   mutate(
#     stack_top = cumsum(percentage),
#     label_y_position = stack_top - (0.5 * percentage)
#   ) |>
#   ungroup() |>
#   group_by(lyrical_topic) |>
#   select(lyrical_topic, label_y_position)

df_midpoints <- tribble(
  ~lyrical_topic      , ~label_y_position ,
  "Bad Relationships" , 0.98              ,
  "Bragging"          , 0.94              ,
  "Dancing"           , 0.88              ,
  "Empowerment"       , 0.80              ,
  "Longing for Love"  , 0.70              ,
  "Lost Love"         , 0.50             ,
  "Love"              , 0.30              ,
  "Lust/Sex"          , 0.22              ,
  "Partying"          , 0.18              ,
  "Other"             , 0.08
)

df_midpoints$color <- c(colors_nizami, "#cccccc")

df_midpoints <-
  df_midpoints |>
  mutate(
    label = glue::glue("<span style='color:{color}'>{lyrical_topic}</span> ")
  )

my_plot <- 
data2plot |>
  ggplot(aes(x = year)) +
  geom_density(
    aes(fill = lyrical_topic),
    alpha = .8,
    position = "fill",
    color = warm_black,
    adjust = 1 / 2,
    show.legend = FALSE
  ) +
  scale_fill_discrete(
    palette = c(colors_nizami, "#CCC")
  ) +
  scale_x_continuous(
    expand = c(0, 0),
  ) +
  scale_y_continuous(
    expand = c(0, 0),
    breaks = df_midpoints$label_y_position,
    labels = df_midpoints$label
  ) +
  theme(
    axis.text.y.left = element_markdown(
      size = 8,
    )
  ) +
  labs(
    x = NULL,
    y = NULL,
    title = str_wrap(
      str_c(
        "**More Bragging and Less Love.** Lyrical topics of Billboard Hot 100 songs evolution"
      ),
      width = 45,
      whitespace_only = FALSE
    ) |>
      glue::glue(
        "<br><br><span style='font-size:12px'>% lyrical topic</span>"
      ) |>
      str_replace_all("\n", "<br>"),
    caption = str_wrap(
      width = 65,
      'SOURCE tidytuesday NOTE This visualization is a conceptual exercise focused on design and layout; it is intended as a stylistic study rather than a comprehensive or final analysis. GITHUB barreiro-r'
    ) |>
      str_replace_all("\n", "<br>"),
  ) +
  guides(
    color = "none",
    alpha = guide_legend(
      position = "bottom",
      override.aes = list(shape = 16),
    )
  )

ggsave(
  my_plot,
  width = 4,
  height = 5.5,
  filename = "2026/images/day19.png"
)
```