---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
output:
    html_document:
        fig_retina: 1
---

# 30 Day Chart Challenge 2026
## Day 25 - Uncertainty: Space

### Load libraries & Set Themes
```{r}
#| label: Load libraries & Set Themes
pacman::p_load(
  tidyverse,
  janitor,
  ggrepel,
  ggtext,
  stringr,
  scales,
  MetBrewer,
  lubridate,
  ggh4x
  # showtext
)

# showtext and ggtext::element_markdown 
# are not behaving properly together
#
# font_add_google(
#   "Hanken Grotesk",
#   "Hanken Grotesk",
#   regular.wt = 400,
#   bold.wt = 800
# )
# showtext_auto()
# showtext_opts(dpi = 300)

warm_white <- "#f0ebe3ff"
warm_black <- "#38352fff"

# MetBrewer::MetPalettes$Nizami
colors_nizami <- c(
  orange_light = "#dd7867",
  red          = "#b83326", 
  orange_dark  = "#c8570d",
  yellow       = "#edb144",
  teal         = "#8cc8bc",
  teal_dark    = "#67a397",
  blue_light   = "#7da7ea",
  blue         = "#5773c0", 
  blue_dark    = "#1d4497"
)

theme_set(
  theme_minimal() +
    theme(
      # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
      # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
      # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(-0.15, "cm"),
      plot.background = element_rect(fill = warm_white),
      plot.title.position = "plot",
      plot.caption.position = "plot",
      plot.title = element_markdown(
        family = "Hanken Grotesk",
        size = 12,
        hjust = 0,
        lineheight = 1.2,
        margin = margin(0, 0, 15, 0),
      ),
      plot.caption = element_markdown(
        family = "Hanken Grotesk",
        size = 8,
        color = 'grey60',
        margin = margin(15, 0, 0, 0),
        hjust = 0,
        lineheight = 1.2
      ),
      plot.subtitle = element_markdown(
        size = 9,
        lineheight = 1.2,
        margin = margin(5, 0, 0, 0),
        hjust = 0.5
      ),
      axis.title.x = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.title.y = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.text = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40"
      ),
      legend.position = "top",
      text = element_text(family = "Hanken Grotesk", color = warm_black),
      plot.margin = margin(25, 25, 25, 25)
    )
)
```


### Read raw data

```{r}
# Loading data
raw_data <- read_csv('2026/datasets/Meteorite_Landings.csv') |>
  janitor::clean_names()
```


### Preparing data for plot
```{r}
data2plot <-
  raw_data |>
  group_by(recclass) |>
  filter(mass_g < quantile(mass_g, 0.75, na.rm = TRUE) + 1.5 * IQR(mass_g, na.rm = TRUE) & mass_g > quantile(mass_g, 0.25, na.rm = TRUE) - 1.5 * IQR(mass_g, na.rm = TRUE)) |>
  ungroup() |>
  mutate(recclass_top10 = fct_lump(recclass, n = 10)) |>
  filter(recclass_top10 != "Other") |>
  mutate(category = case_when(
    str_detect(recclass_top10, "^LL") ~ "Low Metal",
    str_detect(recclass_top10, "^H") ~ "High Iron",
    str_detect(recclass_top10, "^L") ~ "Low Iron",
    str_detect(recclass_top10, "^CM") ~ "Carbonaceous"
  ))

data2plot_stats <-
  data2plot |>
  group_by(recclass_top10, category) |>
  summarise(mass_g_mean = mean(mass_g, na.rm = TRUE)) |>
  ungroup()

data2plot <- 
  data2plot |>
  mutate(recclass_top10 = factor(recclass_top10, levels = data2plot_stats |> arrange(mass_g_mean) |> pull(recclass_top10)))
```


### Time for plotting
```{r fig.showtext=TRUE}
pacman::p_load(ggbeeswarm)

my_plot <-
  data2plot |>
  ggplot(aes(x = recclass_top10, y = log2(mass_g))) +
  ggbeeswarm::geom_quasirandom(
    aes(color = category),
    size = 0.01,
    alpha = 0.5
  ) +
  geom_point(
    data = data2plot_stats,
    aes(y = log2(mass_g_mean)),
    size = 3,
    color = warm_white
  ) +
  geom_point(
    data = data2plot_stats,
    aes(y = log2(mass_g_mean), color = category),
    size = 1.5
  ) +
  scale_y_continuous(
    labels = function(x) {
      glue::glue("2<sup>{x}</sup>")
    },
  ) +
  scale_color_manual(
    values = c(
      "Low Metal" = colors_nizami[["blue_dark"]],
      "High Iron" = colors_nizami[["teal"]],
      "Low Iron" = colors_nizami[["blue_light"]],
      "Carbonaceous" = colors_nizami[["red"]]
    )
  ) +
  theme(
    axis.text.y.left = element_markdown(),
    legend.title.position = "top",
    legend.position = "bottom",
    legend.justification = 0,
    legend.title = element_markdown(size = 8),
    legend.text = element_markdown(size = 7),
    legend.key.spacing = unit(0.1, "lines"),
    legend.location = "plot",
  ) +
  labs(
    x = NULL,
    y = NULL,
    color = "Meteorite Category",
    title = str_wrap(
      glue::glue(
        "**Metorite landings.** A comparison between the mass of the top 10 most common meteorite classes."
      ),
      width = 45,
      whitespace_only = FALSE
    ) |>
      glue::glue(
        "<br><br><span style='font-size:12px'>Mass (grams), each dot represents a meteorite.<br> The bigger the dot represent the mean mass of <br>the meteorite category</span>"
      ) |>
      str_replace_all("\n", "<br>"),
    caption = str_wrap(
      width = 65,
      'SOURCE nasa NOTE This visualization is a conceptual exercise focused on design and layout; it is intended as a stylistic study rather than a comprehensive or final analysis. GITHUB barreiro-r'
    ) |>
      str_replace_all("\n", "<br>"),
  )


ggsave(
  my_plot,
  width = 4,
  height = 5.5,
  filename = "2026/images/day25.png"
)
```