---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
output:
    html_document:
        fig_retina: 1
---

# 30 Day Chart Challenge 2026
## Day 23 - Timeseries: Seasons

### Load libraries & Set Themes
```{r}
#| label: Load libraries & Set Themes
pacman::p_load(
  tidyverse,
  janitor,
  ggrepel,
  ggtext,
  stringr,
  scales,
  MetBrewer,
  lubridate,
  ggh4x
  # showtext
)

# showtext and ggtext::element_markdown 
# are not behaving properly together
#
# font_add_google(
#   "Hanken Grotesk",
#   "Hanken Grotesk",
#   regular.wt = 400,
#   bold.wt = 800
# )
# showtext_auto()
# showtext_opts(dpi = 300)

warm_white <- "#f0ebe3ff"
warm_black <- "#38352fff"

# MetBrewer::MetPalettes$Nizami
colors_nizami <- c(
  orange_light = "#dd7867",
  red          = "#b83326", 
  orange_dark  = "#c8570d",
  yellow       = "#edb144",
  teal         = "#8cc8bc",
  teal_dark    = "#67a397",
  blue_light   = "#7da7ea",
  blue         = "#5773c0", 
  blue_dark    = "#1d4497"
)

theme_set(
  theme_minimal() +
    theme(
      # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
      # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
      # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
      # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.ticks.length = unit(-0.15, "cm"),
      plot.background = element_rect(fill = warm_white),
      plot.title.position = "plot",
      plot.caption.position = "plot",
      plot.title = element_markdown(
        family = "Hanken Grotesk",
        size = 12,
        hjust = 0,
        lineheight = 1.2,
        margin = margin(0, 0, 15, 0),
      ),
      plot.caption = element_markdown(
        family = "Hanken Grotesk",
        size = 8,
        color = 'grey60',
        margin = margin(15, 0, 0, 0),
        hjust = 0,
        lineheight = 1.2
      ),
      plot.subtitle = element_markdown(
        size = 9,
        lineheight = 1.2,
        margin = margin(5, 0, 0, 0),
        hjust = 0.5
      ),
      axis.title.x = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.title.y = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40",
        margin = margin(0, 0, 0, 0)
      ),
      axis.text = element_markdown(
        family = "Hanken Grotesk",
        hjust = 0.5,
        size = 8,
        color = "grey40"
      ),
      legend.position = "top",
      text = element_text(family = "Hanken Grotesk", color = warm_black),
      plot.margin = margin(25, 25, 25, 25)
    )
)
```


### Read raw data

```{r}
# Loading data
raw_data <- read_csv('2026/datasets/monthly-confirmed-cases-of-influenza.csv') |>
  janitor::clean_names()
```


### Preparing data for plot
```{r}
data2plot <-
  raw_data |>
  filter(code %in% c("USA", "AUS")) |>
  mutate(date = day, year = year(date), month = month(date)) |>
  group_by(code, year) |>
  mutate(
    per_influenza = all_strains_all_types_of_surveillance /
      sum(all_strains_all_types_of_surveillance),
  ) |>
  group_by(entity, month) |>

  summarise(
    per_influenza = mean(per_influenza, na.rm = TRUE),
    min_per_influenza = min(per_influenza, na.rm = TRUE),
    max_per_influenza = max(per_influenza, na.rm = TRUE),
    .groups = "drop"
  )
# group_by(entity, month) |>
# summarise(avg_birth_rate = mean(birth_rate_scale)) |>
# ungroup()
```


### Time for plotting
```{r fig.showtext=TRUE}
pacman::p_load(geomtextpath)

grid_data <-
  tribble(
    ~month , ~per_influenza ,
         1 , 0.10           ,
         1 , 0.15           ,
         1 , 0.20           ,
         1 , 0.25
  )

my_plot <- 
data2plot |>
  ggplot(aes(x = month, y = per_influenza)) +
  geom_texthline(
    data = grid_data,
    aes(yintercept = per_influenza, label = percent(per_influenza)),
    size = 2,
    linewidth = 0.2,
    hjust = 0.9,
    alpha = 0.2
  ) +
  # geom_line(data = tibble(month = c(1,1), per_influenza = c(0,1)), aes(color = entity), linewidth = 0.25) +
  geom_col(aes(fill = entity), position = "identity", alpha = 0.5, show.legend = FALSE) +
  # geom_point(aes(color = entity), size = 2) +
  # geom_line(aes(color = entity)) +
  # geom_col(aes(fill = entity), position = "identity", alpha = 0.5) +
  scale_x_continuous(
    breaks = seq(1, 12, 1),
    labels = month.abb,
    # lim = c(1, 12)
    expand = c(0, 0.05)
  ) +
  coord_radial(inner.radius = .3, clip = "off") +
  scale_fill_manual(
    values = c(
      "United States" = colors_nizami[["blue_dark"]],
      "Australia" = colors_nizami[["red"]]
    )
  ) +
  theme(axis.text.y = element_blank()) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Contry",
    title = str_wrap(
      glue::glue(
        "**Influenza cases: Northern vs Southern hemisphere** The peak incidence of influenza follows the season of each hemisphere."
      ) ,
      width = 45,
      whitespace_only = FALSE
    ) |> 
      glue::glue(
        "<br><br><span style='font-size:12px'>% of early influenza cases (<span style='color:{colors_nizami[['blue_dark']]}'>United States</span> / <span style='color:{colors_nizami[['red']]}'>Australia</span>)</span>"
      ) |> str_replace_all("\n", "<br>"),
    caption = str_wrap(
      width = 65,
      'SOURCE our world in data NOTE This visualization is a conceptual exercise focused on design and layout; it is intended as a stylistic study rather than a comprehensive or final analysis. GITHUB barreiro-r'
    ) |>
      str_replace_all("\n", "<br>"),
  ) +
    theme(plot.margin = margin(25, 45, 25, 25))


ggsave(
  my_plot,
  width = 4,
  height = 5.5,
  filename = "2026/images/day23.png"
)
```