---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
---

# 30DayChartChallenge
## Day 09 -  Histogram

```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(scales)
library(MetBrewer)

theme_set(
    theme_minimal() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    panel.grid = element_line(linewidth = .3, color = 'grey90'),
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(family = "Ubuntu", size = 14, face = 'bold'),
    plot.caption = element_text(size = 6, color = '#474747',margin = margin(10,0,0,0)),
    plot.subtitle = element_text(size = 10,lineheight = 1.15, margin = margin(0,0,20,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 9),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 8),
    axis.text = element_markdown(family = "Chakra Petch", hjust = .5, size = 8, color = "#474747"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))

)
```

### Load Data
```{r}
raw_data <- 
    read_csv('2025/datasets/smoking.csv')
```

### Preparing data for plot
```{r}
original_names <- names(raw_data)
names(original_names) <- names(raw_data |> janitor::clean_names())

data2plot <- 
  raw_data |>
  janitor::clean_names() |>
  select(country, year, data_percentage_total ) |>
  rename(smoking_prevalence_percent = 'data_percentage_total') 

data2plot_delta <- 
  data2plot |>
  group_by(country) |>
  mutate(oldest = min(year)) |>
  mutate(newest = max(year)) |>
  ungroup() |>
  mutate(measure_time_categ = NA) |>
  mutate(measure_time_categ = if_else(year == oldest, 'oldest',measure_time_categ)) |>
  mutate(measure_time_categ = if_else(year == newest, 'newest',measure_time_categ)) |>
  filter(!is.na(measure_time_categ)) |>
  pivot_wider(id_cols = country, values_from =smoking_prevalence_percent , names_from = measure_time_categ) |>
  mutate(prevalence_delta = newest - oldest) |>
  mutate(prevalence_status = if_else(prevalence_delta < 0,'Decreased', 'Increased'))

data2plot <- data2plot |> left_join(data2plot_delta, by = 'country')



data2plot <- data2plot |>
  filter(
    country %in% (data2plot_delta |> slice_max(order_by = prevalence_delta, n = 6) |> pull(country)) |
    country %in% (data2plot_delta |> slice_min(order_by = prevalence_delta, n = 6) |> pull(country))
  )

data2plot <- data2plot |> 
  mutate(country = factor(
    country, 
    levels = data2plot_delta |> arrange(prevalence_delta) |> pull(country) |> unique()))

data2plot_delta <- data2plot_delta |>
  mutate(country = factor(
    country, 
    levels = data2plot_delta |> arrange(prevalence_delta) |> pull(country) |> unique()))
```

### Plotting
```{r}
max_value <- max(max(data2plot$prevalence_delta), abs(min(data2plot$prevalence_delta)))

triangle_label_value <- function(delta) {
  ifelse(delta >= 0,
         str_c("\u25B2", round(delta, 2),"%"),           # e.g. "▲ 10"
         str_c("\u25BC", abs(round(delta,2)),"%"))      # e.g. "▼ 2"
}

label_decade <- function(year) {
  # First, determine the “decade start” (e.g., 1970, 1980).
  decade_start <- floor(year / 10) * 10
  
  # Then, take the last two digits of that decade_start
  # and paste an “s” at the end. For instance, 1970 -> 70 -> "70s"
  paste0(decade_start %% 100, "s")
}

data2plot |>
  ggplot(aes(x = year, y = smoking_prevalence_percent)) +
  geom_line(aes(color = prevalence_delta)) +
  geom_area(aes(fill = prevalence_delta), alpha = .2) +
  geom_text_repel(
    data = data2plot_delta |> filter(country %in% data2plot$country), 
    aes(y = 50, label = triangle_label_value(prevalence_delta), color = prevalence_delta),
    x = (min(data2plot$year)+max(data2plot$year))/2,
    force = 0,
    size = 3,
    hjust = 0.5,
    bg.color = 'white', 
    segment.size = 0,
    bg.r = 0.3) +
  geom_text_repel(
    data = data2plot_delta |> filter(country %in% data2plot$country), 
    aes(y = oldest + 5, label = str_c(round(oldest),"%"), color = prevalence_delta),
    x = min(data2plot$year),
    force = 0,
    size = 3,
    hjust = 0,
    bg.color = 'white', 
    segment.size = 0,
    bg.r = 0.3) +
  geom_text_repel(
    data = data2plot_delta |> filter(country %in% data2plot$country), 
    aes(y = newest + 5, label = str_c(round(newest),"%"), color = prevalence_delta),
    x = max(data2plot$year),
    force = 0,
    size = 3,
    hjust = 1,
    bg.color = 'white', 
    segment.size = 0,
    bg.r = 0.3) +
    # 1) Annotate the min_year at bottom-left
  annotate(
    "text",
    x = min(data2plot$year),
    y = 0,
    label = min(data2plot$year),
    hjust = 0,   # left-justify horizontally
    vjust = -0.5,
    size = 2,
    color = 'grey60'
  ) +
  
  # 2) Annotate the max_year at bottom-right
  annotate(
    "text",
    x = max(data2plot$year),
    y = 0,
    label = max(data2plot$year),
    hjust = 1,   # right-justify horizontally
    vjust = -0.5, 
    size = 2,
    color = 'grey60'
  ) +
  facet_wrap(~country, ncol = 6) +
  scale_color_gradientn(colours = ggsci::pal_frontiers()(5) |> rev(), limits = c(-max_value,max_value)) +
  scale_fill_gradientn(colours = ggsci::pal_frontiers()(5) |> rev(), limits = c(-max_value,max_value)) +
  theme(panel.spacing.x = unit(.5, "lines"),
    axis.text.x = element_blank(),
    ) +
  scale_y_continuous(breaks = c(0, 25, 50), labels = function(x) paste0(x, "%")) +
  labs(
    title = 'Global Smoking Trends: Top 5 Biggest Increases and Decreases (1980–2012)',
    subtitle = 'A comparative look at the five countries with the largest rises and falls in smoking prevalence',
    x = NULL,
    y = 'Smoking Prevalence'
  ) +
  guides(color = 'none', fill = 'none')
```

