---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
---

# 30DayChartChallenge
## Day 10 -  Multi-modal

```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(scales)
library(MetBrewer)

theme_set(
    theme_minimal() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    panel.grid = element_line(linewidth = .3, color = 'grey90'),
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(family = "Ubuntu", size = 14, face = 'bold'),
    plot.caption = element_text(size = 6, color = '#474747',margin = margin(10,0,0,0)),
    plot.subtitle = element_text(size = 10,lineheight = 1.15, margin = margin(0,0,20,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 9),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 8),
    axis.text = element_markdown(family = "Chakra Petch", hjust = .5, size = 8, color = "#474747"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))

)
```

### Preparing data for plot
```{r}
# Need to re-run multiple times until pretty.
my_data <- 
  bind_rows(
    tibble(x = rnorm(1200,mean = 0, sd = 3), group = 'Elephant'),
    tibble(x = rnorm(1000,mean = 8, sd = 3), group = 'Snake'),
    tibble(x = rep(seq(-15,21,1),60), group = 'Snake'))

my_data <- bind_rows(
  my_data |> mutate(facet_group = "B"),
  my_data |> mutate(group = 'Hat') |> mutate(facet_group = "A")
)

library(ggh4x)

my_plot <- 
  my_data |>
  ggplot(aes(x = x, fill = group)) +
  geom_density(bw = 1, color = NA) +
  coord_cartesian(ylim = c(0.017,0.15)) +
  facet_wrap(~facet_group) +
  scale_fill_manual(values = c('Hat'='#593533', 'Snake' = '#109e2a', 'Elephant' = 'grey70')) +
  theme(
      axis.text = element_blank(),
      legend.title =  element_text(size=8, face = 'bold', color = "grey10"),
      legend.spacing = unit(0.1, 'cm'),
      legend.key.height= unit(0.5, 'cm'),
      legend.key.width= unit(0.8, 'cm'),
      strip.text = element_blank(),      # Remove the facet label text
      strip.background = element_blank() # Remove the background behind labels
  ) 


annotation_elephant_arrow <- annotate(
    geom = "curve", x = -3, y = .11, xend = -4, yend = .13,
    curvature = -.3, arrow = arrow(length = unit(2, "mm"))
  ) 

annotation_elephant_text <- annotate(
  geom = 'text', y = .14, x = -3.8, 
  label = 'Elephant', hjust = 0, family = 'Ubuntu'
)

annotation_snake_arrow <- 
  annotate(
    geom = "curve", x = 13, y = .04, xend = 13, yend = .07,
    curvature = .3, arrow = arrow(length = unit(2, "mm"))
  ) 

annotation_snake_text <- 
  annotate(
    geom = "text",x = 8, y = .08,
    label = 'Snake', hjust = 0, family = 'Ubuntu'
  ) 

annotation_hat_arrow <- 
  annotate(
    geom = "curve", x = -4, y = .04, xend = 0, yend = .07,
    curvature = -.5, arrow = arrow(length = unit(2, "mm"))
  ) 

annotation_hat_text <- 
  annotate(
    geom = "text",x = 1, y = .070,
    label = 'Hat', hjust = 0, family = 'Ubuntu'
  )   

my_plot + 
  at_panel(annotation_elephant_arrow, facet_group == 'B') +
  at_panel(annotation_elephant_text, facet_group == 'B') +
  at_panel(annotation_snake_arrow , facet_group == 'B') +
  at_panel(annotation_snake_text , facet_group == 'B') +
  at_panel(annotation_hat_arrow , facet_group == 'A') +
  at_panel(annotation_hat_text , facet_group == 'A') +
  guides(fill = 'none') +
  labs(
    x = NULL, 
    y = "Density", 
    title = "Beyond the Hat", 
    subtitle = "Discovering the Elephant in the Multimodal Room.\nBoth sides are made of the exact same data!")
```
