---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
---

# 30DayChartChallenge
## Day 17 - El País

```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(scales)
library(MetBrewer)
library(lubridate)
library(ggh4x)

theme_set(
    theme_minimal() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(family = "Ubuntu", size = 18, face = 'bold'),
    plot.caption = element_text(size = 8, color = '#474747',margin = margin(10,0,0,0)),
    plot.subtitle = element_markdown(size = 11,lineheight = 1.15, margin = margin(0,0,15,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.text = element_markdown(family = "Ubuntu", hjust = .5, size = 10, color = "#474747"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))
)
```


### Preparing data for plot
```{r}
raw_data <- readr::read_csv('2025/datasets/finch_beaks_1975.csv') |>
  janitor::clean_names()

data_summary <- 
  raw_data |> 
  group_by(species) |>
   summarise(min_beak = min(beak_length_mm), max_beak = max(beak_length_mm)) |>
   pivot_longer(cols = -species, names_to = 'categ', values_to = 'lenght')

data_summary_wide <- 
  raw_data |> 
  group_by(species) |>
   summarise(min_beak = min(beak_length_mm), max_beak = max(beak_length_mm))
```

```{r}
raw_data |>
  ggplot(aes(x = beak_length_mm)) +

  # Geometries
  geom_histogram(
    aes(y = after_stat(density), fill = species), 
    bins = 50
  ) +
  geom_text(
    data = data_summary_wide, 
    aes(label = min_beak, x = min_beak, color = species), 
    hjust = 1.1, y = .7
  ) +
  geom_text(
    data = data_summary_wide, 
    aes(label = max_beak, x = max_beak, color = species), 
    hjust = -0.1, y = .7
  ) +
  geom_segment(
    data = data_summary_wide, 
    aes(x = min_beak, xend = max_beak, color = species), 
    y = .7 
  ) +
  geom_hline(yintercept = 0, linewidth = .15, color = 'black') +

  # Faceting
  facet_grid(species ~ .) +

  # Annotations
  at_panel(
    annotate(
      "text", x = 12, y = 0.24, label = "G. fortis", size = 4,
      hjust = 0, color = "#B9486D", family = 'Ubuntu', 
      fontface = 'bold.italic'
    ),
    PANEL %in% c(1)
  ) +
  at_panel(
    annotate(
      "text", x = 15.5, y = 0.24, label = "G. scandens", size = 4,
      hjust = 0, color = "#4A866A", family = 'Ubuntu', 
      fontface = 'bold.italic'
    ),
    PANEL %in% c(2)
  ) +

  # Scales
  scale_fill_manual(values = c("#B9486D", "#4A866A")) +
  scale_color_manual(values = c("#B9486D", "#4A866A")) +
  scale_x_continuous(
    limits = c(8, 18),
    breaks = seq(8, 18, 2),
    label = function(x) { 
      ifelse(x == 18, paste0(x, "mm"), as.character(x)) 
    }
  ) +

  # Theme
  theme(
    axis.text.y = element_blank(),
    axis.text.x = element_text(color = 'grey70'),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    legend.position = 'none',
    strip.text = element_blank(),
    strip.background = element_blank()
  ) +

  # Labels
  labs(
    subtitle = str_wrap(
      paste0(
        "**Beak size of Darwin's finches.** In 1973, Peter and ",
        "Rosemary Grant visited the Galápagos island of Daphne Major ",
        "and collected data on Darwin's finches, to study Darwin's ",
        "theory of evolution."
      ), 
      width = 65
    ) |> str_replace_all('\n', '<br>'),
    caption = "SOURCE Kaggle Darwin's Finches Evolution"
  )
 ```
