---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
---

# 30DayChartChallenge
## Day 16 -  Negative

```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(scales)
library(MetBrewer)
library(lubridate)
library(ggh4x)

theme_set(
    theme_minimal() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(family = "Ubuntu", size = 18, face = 'bold'),
    plot.caption = element_text(size = 8, color = '#474747',margin = margin(10,0,0,0)),
    plot.subtitle = element_text(size = 10,lineheight = 1.15, margin = margin(0,0,5,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.text = element_markdown(family = "Ubuntu", hjust = .5, size = 10, color = "#474747"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))
)
```


### Preparing data for plot
```{r}
library(geofacet)
library(ggchicklet)

raw_data <- read_csv('2025/datasets/police_fatalities.csv') |>
  select(`Location of death (state)`,`Date (Year)`) |>
  rename(state = "Location of death (state)", year = "Date (Year)")


states <- read_csv('2025/datasets/Police Fatalities.csv') |> select(State)

data2plot <- 
  raw_data |>
  filter(!is.na(year)) |>
  count(year, state) |>
  filter(state %in% states$State) |>
  pivot_wider(names_from = state, values_from = n,values_fill = 0) |>
  pivot_longer(names_to = 'state', values_to = 'n', cols = -year)

data2plot |> count(year)

data2plot |>
  ggplot(aes(x = year, y = 0, yend = -n)) +
  geom_segment(aes(color = n), lineend = "round", linewidth = 1.2) +
  facet_geo(~ state, grid = "us_state_grid1", strip.position = "top") +
  scale_y_continuous(label = abs, expand = c(0.1,0,0,0)) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    strip.text = element_text(
        hjust = 0,
        color = "grey20"
        ),
    legend.justification = c(0, 1)
  ) +
  scale_color_gradientn(
    colours = c('#eb4242', '#d11b1b', '#540303'),
    breaks = c(0, max(data2plot$n))) +
  labs(
    title = "Fatal Encounters",
    x = NULL, 
    y = NULL,
    color = 'Fatalities',
    caption  = 'SOURCE Kaggle Police Fatalities in the US From 2000 To 2020',
    subtitle = str_wrap("Exploring patterns using data from the pioneering Fatal Encounters project, which compiles public records of lethal force incidents. Data from 2000 to 2020", width = 80)) +
  guides(
    color = guide_colorbar(
      barwidth = 13,
      barheight = .3,
      title.position = "top",
      label.position = "bottom",
      position = 'top',
    )
  )


```
