---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
---

# 30DayChartChallenge
## Day 12 -  Data.gov

```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(scales)
library(MetBrewer)
library(lubridate)
library(ggh4x)

theme_set(
    theme_minimal() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    # panel.grid = element_line(linewidth = .3, color = 'grey90'),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(family = "Ubuntu", size = 18, face = 'bold'),
    plot.caption = element_text(size = 8, color = '#474747',margin = margin(10,0,0,0)),
    plot.subtitle = element_text(size = 10,lineheight = 1.15, margin = margin(0,0,20,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.text = element_markdown(family = "Ubuntu", hjust = .5, size = 10, color = "#474747"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))

)
```


### Preparing data for plot
```{r}
raw_data <- 
  read_csv('2025/datasets/adult-depression-lghc-indicator-24.csv') |>
  janitor::clean_names()
```



```{r}
income_classes <- 
  raw_data |>
  filter(strata == "Income") |>
  filter(year == 2012) |>
  pull(strata_name)

data2plot <- 
  raw_data |> 
  filter(strata == "Income") |>
  mutate(strata_name = factor(strata_name, levels = income_classes)) |>
  select(year, strata_name, percent) |>
  rename(income_strata = 'strata_name')
```

```{r}
data2plot |>
  ggplot(aes(x = year, y = income_strata)) +
  geom_tile(
    aes(fill = percent)) +
  coord_fixed() +
  scale_x_continuous(
    breaks = seq(min(data2plot$year), max(data2plot$year), 1),
    expand = c(0,0.1,0,0)
  ) +
  labs(
    x = NULL,
    y = 'Annual Household Income<br>'
  ) +
  viridis::scale_fill_viridis(
    option = 'magma', 
    direction = -1,
    breaks = c(min(data2plot$percent),max(data2plot$percent)),
    label = function(x) str_c(round(x),"%")) +
  guides(
    fill = guide_colorbar(
      barwidth = 13,
      barheight = .5,
      title.position = "top",
      label.position = "bottom",
    )
  ) +
  labs(
    title = "Adult Depression Prevalence by Income in California",
    subtitle = str_wrap('Proportion of adults ever diagnosed with a depressive disorder, shown by annual household income level, based on data from the California Behavioral Risk Factor Surveillance Survey (BRFSS).', width = 100),
    fill = 'Adults who were told they had a depressive disorder',
    caption = "SOURCE Data.gov - Adult Depression (LGHC Indicator)"
  ) +
  theme(
    legend.title = element_text(size = 8, hjust = .5),
    legend.text = element_text(size = 8, hjust = .5),
  )
```
