---
title: "Breast Cancer Wisconsin"
format: html
echo: false
warning: false
message: false
---


```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(waffle)

theme_set(
    theme_minimal() +
    theme(
    axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    panel.grid = element_line(linewidth = .3, color = 'grey80'),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_markdown(family = "Ubuntu", size = 15),
    plot.subtitle = element_markdown(size = 9,lineheight = 1.25, margin = margin(0,0,20,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 9),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 8),
    axis.text = element_markdown(family = "Chakra Petch", hjust = .5, size = 8, color = "#474747"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))
)
```

```{r load_data}
data2plot <- 
    read_csv('2025/datasets/student-mental-stress-and-coping-mechanisms.csv')

pretty_name <- c(data2plot |> names())
names(pretty_name) <- data2plot |> janitor::clean_names() |> names()

data2plot <- 
    data2plot |>
    janitor::clean_names() |>
    mutate(gender = if_else(gender %in% c("Female","Male"), gender, 'Non-binary'))

most_popular_coping <- 
    data2plot |>
    count(stress_coping_mechanisms, sort = TRUE) |>
    slice_max(n = 7, order_by = n) |>
    pull(stress_coping_mechanisms)


data2plot |>
    count(stress_coping_mechanisms, gender, sort = TRUE) |>
    filter(stress_coping_mechanisms %in% most_popular_coping) |>
    ggplot(aes(fill = stress_coping_mechanisms, values = n)) +
    geom_waffle(color = "white", size = .25, flip = TRUE, n_rows = 10, make_proportional = FALSE) +
    facet_wrap(~gender, nrow = 1, strip.position = "bottom") +
    MetBrewer::scale_fill_met_d("Hiroshige", direction=1) +
    coord_equal() +
    scale_x_discrete(expand = c(.15,.15)) + 
    scale_y_continuous(labels = function(x) x * 10, # make this multiplyer the same as n_rows
                        expand = c(0,0)) +
    theme(
        axis.line.y.left = element_blank(),
        axis.ticks.y = element_blank(),
        # Legend
        legend.position = c(1,1),
        legend.justification = c(1,1),
        legend.title =  element_text(size=8, face = 'bold', color = "grey10"),
        legend.spacing = unit(0.1, 'cm'),
        legend.key.height= unit(0.3, 'cm'),
        legend.key.width= unit(0.5, 'cm'),
        legend.text = element_text(size=6, face = 'plain', color = "grey10"),
        legend.background = element_rect(fill = 'white', size = 0)) +
    labs(
        y = 'Students (n)', 
        fill = 'Stress coping mechanisms', 
        title = "**Stress Coping Mechanisms Among University Students**",
        subtitle = str_wrap('Each square represents one student. While yoga and walking are popular across all genders, males report higher engagement in watching sports, whereas social media use appears more prevalent among females and non-binary students.', width = 80) |> str_replace_all("\n", "<br>"))


```
