---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
---

# 30DayChartChallenge
## Day 19 - Smooth

```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(scales)
library(MetBrewer)
library(lubridate)
library(ggh4x)

theme_set(
    theme_minimal() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(family = "Ubuntu", size = 18, face = 'bold'),
    plot.caption = element_text(size = 8, color = 'grey60',margin = margin(10,0,0,0)),
    plot.subtitle = element_markdown(size = 11,lineheight = 1.15, margin = margin(0,0,15,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.text = element_markdown(family = "Chakra Petch", hjust = .5, size = 8, color = "grey70"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))
)
```


### Preparing data for plot
```{r}
raw_data <- read_csv('2025/datasets/student_habits_performance.csv') |>
  janitor::clean_names()
```

```{r}
data2plot <- 
  raw_data |>
  select(country_name, continent, starts_with('forest')) |>
  pivot_longer(cols = -c(country_name, continent), names_to = 'forest_year', values_to = 'area') |>
  mutate(year = str_replace(forest_year,'.*_','') |> as.numeric())

area_start <- 
  data2plot |>
  group_by(country_name)

```

```{r}
my_palette <- colorRampPalette(c("#B3CDD9", "#4692B0", "#093351"))(10)

raw_data |>
  mutate(mental_health_rating = factor(mental_health_rating, levels = seq(1, 10))) |>
  ggplot(aes(x = study_hours_per_day, y = exam_score)) +

  # Geometries
  geom_point(
    aes(fill = as.numeric(mental_health_rating), 
        color = mental_health_rating), 
    size = 1
  ) +
  geom_smooth(
    aes(group = mental_health_rating), 
    color = 'white', linewidth = 2, method = 'lm', se = FALSE, alpha = .1
  ) +
  geom_smooth(
    aes(color = mental_health_rating),
    linewidth = .5, method = 'lm', se = FALSE, alpha = .1
  ) +

  # Scales
  scale_color_manual(values = my_palette) +
  scale_fill_gradientn(colors = my_palette, breaks = c(1, 10)) +
  scale_y_continuous(limits = c(0, 100)) +

  # Guides
  guides(
    color = 'none',
    fill = guide_colorbar(
      barwidth = 7,
      barheight = .3
    )
  ) +

  # Theme
  theme(
    legend.position = c(0.96, 0.05),
    legend.justification = c(1, 0),
    legend.direction = 'horizontal',
    legend.title.position = 'top',
    legend.title = element_text(size = 8, hjust = .5)
  ) +

  # Labels
  labs(
    x = "Study Hours per Day", 
    y = "Exam Score", 
    fill = 'Mental Health Rating', 
    title = "Student Habits vs Academic Performance", 
    subtitle = 'The Combined Impact of Study Time and Mental Well-being',
    caption = 'SOURCE Kaggle Student Habits vs Academic Performance'
  )

```

 
