---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
---

# 30DayChartChallenge
## Day 17 - Birds

```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(scales)
library(MetBrewer)
library(lubridate)
library(ggh4x)

theme_set(
    theme_minimal() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(family = "Ubuntu", size = 18, face = 'bold'),
    plot.caption = element_text(size = 8, color = '#474747',margin = margin(10,0,0,0)),
    plot.subtitle = element_text(size = 10,lineheight = 1.15, margin = margin(0,0,5,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.text = element_markdown(family = "Ubuntu", hjust = .5, size = 10, color = "#474747"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))
)
```


### Preparing data for plot
```{r}
bird_baths <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2021/2021-08-31/bird_baths.csv')


data2plot <-
  bird_baths %>%
  filter(complete.cases(.)) %>%
  group_by(bird_type, urban_rural, survey_year) %>% 
  summarise(n = sum(bird_count)) %>%
  pivot_wider(names_from = urban_rural, values_from = n) %>%
  mutate(pct_urban = Urban/(Rural+Urban)) %>%
  filter(Urban > 0 & Rural > 0) %>%
  group_by(bird_type) %>%
  filter(n() == 2) %>%
  ungroup()

my_order <-
  data2plot %>%
  mutate(survey_year = as.character(survey_year)) %>%
  select(-Rural, -Urban) %>%
  pivot_wider(names_from = survey_year, values_from = pct_urban) %>%
  mutate(delta = `2014`-`2015`)

moving_to_city <-
  my_order %>%
  filter(delta < 0) %>%
  pull(bird_type)

moving_to_camp <-
  my_order %>%
  filter(delta > 0) %>%
  pull(bird_type)

allow_list_bird_moving_to_city <-
  data2plot %>%
  filter(bird_type %in% moving_to_city) %>%
  mutate(n = Rural + Urban) %>%
  group_by(bird_type) %>%
  summarise(total_n = sum(n)) %>%
  slice_max(total_n, n = 10, with_ties = FALSE) %>%
  pull(bird_type) %>% unique()

allow_list_bird_moving_to_camp <-
  data2plot %>%
  filter(bird_type %in% moving_to_camp) %>%
  mutate(n = Rural + Urban) %>%
  group_by(bird_type) %>%
  summarise(total_n = sum(n)) %>%
  slice_max(total_n, n = 10, with_ties = FALSE) %>%
  pull(bird_type) %>% unique()

my_order <-
  my_order %>%
  filter(
    bird_type %in% c(allow_list_bird_moving_to_city, allow_list_bird_moving_to_camp)) %>%
  arrange(delta) %>%
  pull(bird_type) %>% 
  unique()


```


```{r}
data2plot %>%
  filter(
    bird_type %in% c(allow_list_bird_moving_to_city, allow_list_bird_moving_to_camp)) %>%
  mutate(survey_year = as.character(survey_year)) %>%
  mutate(moving = if_else(bird_type %in% allow_list_bird_moving_to_city, 'Moving to city bird baths', 'Moving to camp bird baths')) %>%
  mutate(moving = toupper(moving)) %>%
  ggplot(aes(x = factor(bird_type, levels = c(my_order)), y = pct_urban, )) +
  geom_point(size = 4, aes(color = survey_year), alpha = .3) +
  geom_line(aes(group = bird_type), color = 'black', size = .5,
            arrow = arrow(length=unit(0.10,"cm"), ends="last", type = "closed")) +
  geom_hline(yintercept = 0.5, color = 'grey60') +
  facet_wrap(. ~ moving, scales = 'free_y') +
  scale_y_continuous(limits = c(0,1), labels = scales::percent) +
  coord_flip() +
  labs(x = NULL, y = "**Birds spotted in cities bird baths** (%)", title = "Moving Out!",
       subtitle = "Some birds decided to find a new place to bathe in 2015.",
       color = NULL,
       caption = 'SOURCE TidyTuesday 2021.08.31 Bird species were filtered by highest birds spotted') +
  theme(legend.position = 'bottom')


```
