---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
---

# 30DayChartChallenge
## Day 19 - Smooth

```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(scales)
library(MetBrewer)
library(lubridate)
library(ggh4x)

theme_set(
    theme_minimal() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(family = "Ubuntu", size = 18, face = 'bold'),
    plot.caption = element_text(size = 8, color = 'grey60',margin = margin(10,0,0,0)),
    plot.subtitle = element_text(size = 11,lineheight = 1.15, margin = margin(0,0,15,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.text = element_markdown(family = "Chakra Petch", hjust = .5, size = 8, color = "grey70"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))
)
```


### Preparing data for plot
```{r}
raw_data <- read_csv('2025/datasets/central_west.csv') |>
  janitor::clean_names() |>
  select(data, temperatura_do_ar_bulbo_seco_horaria_c, state) |>
  filter(state %in% c("DF", "GO"))
```

```{r}
data2plot <-
  raw_data |>
  filter(state == "DF") |>
  filter(temperatura_do_ar_bulbo_seco_horaria_c > 0) |> 
  group_by(state, data) |>
  summarise(
    min_temp = min(temperatura_do_ar_bulbo_seco_horaria_c),
    max_temp = max(temperatura_do_ar_bulbo_seco_horaria_c)
  ) |>
  ungroup() |>
  filter(year(data) != min(year(data))) |>
  filter(year(data) != max(year(data))) |>
  mutate(avg_temp = (min_temp + max_temp)/2) |>
  filter((year(data) == max(year(data))) | (year(data) == min(year(data))))
```

```{r}
palette_colors <- c(
  "#D1D7FF", # Light lavender/blue start
  "#9B51E0", # Purple
  "#2D30D9", # Deep Blue
  "#2F80ED", # Medium Blue
  "#56CCF2", # Light Blue / Cyan
  "#6FCF97", # Aqua Green
  "#F2FFED", # Very Pale Yellow/Greenish white
  "#F2C94C", # Yellow/Gold
  "#F2994A", # Orange
  "#EB5757", # Red
  "#8B0000", # Dark Red / Maroon
  "#000000"  # Black end
)

palette <- c(
   "#32649e", "#68b6c0",
  "#bee7bb", "#f9f0b8", "#ef9754", "#c63130", "#220a11"
)

data2plot |>
  mutate(year = year(data)) |>
  mutate(data = update(data, year = 2000)) |>
  ggplot(aes(x = data, y = min_temp)) +
  geom_segment(aes(y = min_temp, yend = max_temp, color = avg_temp)) +
  facet_grid(~year) +
  coord_radial() +
  scale_color_gradientn(
    colors = palette, 
    breaks = c(min(data2plot$avg_temp),max(data2plot$avg_temp)),
    label = function(x){str_c(x,"ºC")}) +
  scale_y_continuous(limits = c(0, 40), expand = c(0,0,0.05,0)) +
  geom_hline(yintercept = 10, linewidth = .25, color = '40', alpha = .7) +
  annotate(geom = 'text', y = 10-3, label = '10ºC', x = date('2000/01/01'), size = 2, color = 40) +
  geom_hline(yintercept = 20, linewidth = .25, color = '40', alpha = .7) +
  geom_hline(yintercept = 30, linewidth = .25, color = '40', alpha = .7) +
  geom_hline(yintercept = 40, linewidth = .25, color = '40', alpha = .7) +
  annotate(geom = 'text', y = 40-3, label = '40ºC', x = date('2000/01/01'), size = 2, color = 40) +
  scale_x_date(
    expand = c(0,0),
    date_breaks = "1 month",
    date_labels = "%b"  # e.g., Jan, Feb, Mar
  ) +
  labs(
    x = NULL, 
    y = NULL,
    color = "Daily Avg Temperature",
    title = "Brasilia Temperature Shift",
    subtitle = str_wrap("Between 2001 and 2020, rapid urbanization in Brasília led to a noticeable increase in temperature amplitude, as intensified land use and reduced vegetation cover heightened both daytime heating and nighttime cooling.", width = 80),
    caption = "SOURCE Kaggle Climate Weather Surface of Brazil - Hourly \n Plot inspiration: github.com/dominicroye"
  ) +
  theme(
    axis.text.y = element_blank(),
    legend.title = element_text(size = 8),
    legend.justification = c(0,1)
  ) +
  guides(
    color = guide_colorbar(
      barwidth = 13,
      barheight = .3,
      title.position = 'top'
    )
  ) 



```

 
