---
title: "#30DayChartChallenge"
format: html
echo: false
warning: false
message: false
---

# 30DayChartChallenge
## Day 21 - Fossils

```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(scales)
library(MetBrewer)
library(lubridate)
library(ggh4x)

theme_set(
    theme_minimal() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    # # panel.grid = element_line(linewidth = .3, color = 'grey90'),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(family = "Ubuntu", size = 18, face = 'bold'),
    plot.caption = element_text(size = 8, color = 'grey60',margin = margin(10,0,0,0)),
    plot.subtitle = element_text(size = 11,lineheight = 1.15, margin = margin(0,0,15,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 10),
    axis.text = element_markdown(family = "Chakra Petch", hjust = .5, size = 8, color = "grey70"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))
)
```


### Preparing data for plot
```{r}
raw_data <- read_csv('2025/datasets/reviews_data.csv') |>
  janitor::clean_names() 
```

```{r}
data2plot <- 
  raw_data |>
  transmute(
    rating = as.character(rating), 
    year = as.numeric(str_replace(date,'.*, ',''))) |>
  filter(rating != "N/A") |>
  count(rating, year) |>
  mutate(rating = as.numeric(rating)) |>
  group_by(year) |>
  arrange(rating, .by_group = TRUE) |>
  mutate(
    max_n = cumsum(n),        
    min_n = max_n - n         
  ) |>
  ungroup() |>
  select(year, rating, min_n, max_n) |>
  mutate(rating_label = strrep("★", rating))

data2plot <- data2plot |>
  mutate(rating_factor = factor(rating))

star_label <- data2plot |>
  distinct(rating_label) |>
  pull(rating_label) |>
  sort()
names(star_label) <- data2plot |>
  distinct(rating_factor) |>
  pull(rating_factor) |>
  sort()

```

```{r}
png("2025/images/day22.png", type = "cairo", width = 2000, height = 1600, res = 300)

ggplot(data2plot, aes(y = year)) +
  geom_point(aes(x = min_n, color = rating_factor), alpha = 0, shape = 19, size = 4) +
  geom_segment(aes(x = min_n, xend = max_n, color = rating_factor), linewidth = 4, lineend = 'round', show.legend = FALSE) +
  scale_x_continuous(expand = c(0.04, 0, 0.04, 0)) +
  scale_y_continuous(breaks = seq(min(data2plot$year), max(data2plot$year), 1)) +
  scale_color_manual(
    labels = star_label,
    values = rev(c("#1cb05a", "#92d3ad", "#F2C94C", "#F2994A", "#EB5757"))
  ) +
  labs(
    title = "Starbucks Reviews",
    subtitle = "I guess people review only when they are angry.",
    x = "Reviews",
    y = NULL,
    color = NULL,
    caption = "SOURCE Kaggle Starbucks Reviews Dataset"
  ) +
  guides(color = guide_legend(
    override.aes = list(alpha = 1)
  )) +
  theme(
    legend.position = 'bottom'
  )

dev.off()
```
