---
title: "Breast Cancer Wisconsin"
format: html
echo: false
warning: false
message: false
---


```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(lubridate)
library(scales)



theme_set(
    # theme_minimal() +
    theme_void() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    # panel.grid = element_line(linewidth = .3, color = 'grey80'),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "panel",
    plot.title = element_text(family = "Ubuntu", face = 'bold', size = 15, margin = margin(0,0,5,0),hjust = .5),
    plot.subtitle = element_text(size = 9,lineheight = 1.25, margin = margin(0,0,10,0), hjust = .5),
    axis.title.x = element_text(family = "Ubuntu", hjust = .5, size = 9),
    axis.title.y = element_text(family = "Ubuntu", hjust = .5, size = 8),
    axis.text = element_text(family = "Chakra Petch", hjust = .5, size = 8, color = "#474747"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))
)
```

```{r load_data}
data2plot <- 
    read_csv('2025/datasets/dengue-cases-in-the-philippines.csv')

colors <- c(
  "#2C003E",
  "#2D5F8C",
  "#BDC2C4",
  "#D98A59",
  "#781B1F",
  "#40001C" 
)

data2plot |>
    janitor::clean_names() |>
    mutate(dengue_cases = if_else(dengue_cases > 5000, 5000, dengue_cases)) |>
    mutate(month = factor(month, levels = month.name)) |>
    ggplot(aes(x = month, y = dengue_cases)) +
    geom_point(position = position_jitter(width = 1), aes(color = dengue_cases), size = 1) +
    coord_polar(clip = "off") +
    scale_color_gradientn(colors = colors, label = label_number(scale_cut = cut_short_scale()), breaks = c(0,5000), limits = c(0,5000)) +
    scale_y_continuous(limits = c(-3000,7000)) +
    theme(axis.text.y = element_blank()) +
    labs(x = NULL, y = NULL, color = 'Dengue Cases',
        title = "Dengue Cases in the Philippines",
        subtitle = "Monthly dengue case distribution across regions (2016–2020)") +
    theme(
        legend.position = 'bottom',
        legend.direction = 'horizontal',
        legend.key.height = unit(3,'mm'),
        legend.title.position = 'top',
        legend.title = element_text(hjust = .5, size = 8),
        legend.text = element_text(hjust = .5, size = 8))


```
