---
title: "Breast Cancer Wisconsin"
format: html
echo: false
warning: false
message: false
---


```{r setup}
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(stringr)
library(scales)

theme_set(
    theme_minimal() +
    theme(
    # axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    # axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    # axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    panel.grid = element_line(linewidth = .3, color = 'grey90'),
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(family = "Ubuntu", size = 14, face = 'bold'),
    plot.subtitle = element_markdown(size = 10,lineheight = 1.25, margin = margin(0,0,20,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 9),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 8),
    axis.text = element_markdown(family = "Chakra Petch", hjust = .5, size = 8, color = "#474747"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))

)
```

```{r load_data}
pokemon_df <- 
  read_csv('2025/datasets/pokemon.csv') |>
  select(pokemon, height, type_1, generation_id, color_1) |>
  filter(generation_id == 1, type_1 %in% c('fire','grass','water')) |>
  mutate(image_path = glue::glue("2025/datasets/pokemon-images/{pokemon}.png")) |>
  filter(pokemon != 'gyarados') |>
  filter(pokemon != 'moltres')

library('ggimage')

transparent <- function(img) {
  magick::image_fx(img, expression = "0.1*a", channel = "alpha")
}

max_height <- pokemon_df |> pull(height) |> max()

min_height_pokemon <- 
  pokemon_df |>
  group_by(type_1) |>
  slice_min(order_by = height, n = 1, with_ties = FALSE)

max_height_pokemon <- 
  pokemon_df |>
  group_by(type_1) |>
  slice_max(order_by = height, n = 1, with_ties = FALSE)

extreme_pokemons <- bind_rows(max_height_pokemon, min_height_pokemon)

pokemon_df |>
  ggplot(aes(x = type_1, y = height)) +
  geom_image(
    aes(image=image_path, color = type_1, y = height/2, size = I(height/max_height)),
    image_fun = transparent, by="height") +
  geom_image(
    data = max_height_pokemon,
    aes(image=image_path, y = height/2, size = I(height/max_height)),
    by="height",nudge_x = .2)+ 
  geom_image(
    data = min_height_pokemon,
    aes(image=image_path, y = height/2, size = I(height/max_height)),
    by="height",nudge_x = -.2)+ 
  geom_errorbar(
    data = max_height_pokemon, 
    aes(ymin = 0, ymax = height), 
    position = position_nudge(x = .3),
    width = .035,
    color = 'grey10',
    linewidth = .3) +
  geom_text_repel(
    data = max_height_pokemon, 
    aes(label = str_c(height,'m'), y = height/2), 
    position = position_nudge(x = .3), 
    hjust = -.8, 
    bg.color = 'white', 
    bg.r = 0.3,
    size = 3) +
  geom_errorbar(
    data = min_height_pokemon, 
    aes(ymin = 0, ymax = height), 
    position = position_nudge(x = -.33),
    width = .035,
    color = 'grey10',
    linewidth = .3) +
  geom_text_repel(
    data = min_height_pokemon, 
    aes(label = str_c(height,'m'), y = height/2), 
    position = position_nudge(x = -.33), 
    hjust = 0, 
    bg.color = "white", 
    bg.r = 0.2,
    size = 3) +
  coord_cartesian(ylim = c(0,max_height)) +
  scale_x_discrete(expand = c(.4,0,.4,0), label = str_to_sentence) +
  scale_color_manual(values = c("#F08030", "#78C850", "#6890F0")) +
  guides(color = FALSE) +
  labs(
    y = '**Height** (m)',
    x = NULL,
    title = "1st Generation Pokemon Height",
    subtitle = "Legendary Pokémon were excluded for fairness (and so was Gyarados, because it's a giant flying water worm).")
 ```
