project:
  type: default

website: 
  title: "30DayChartChallange"
  favicon: star-of-life-solid.svg

format:
  html:
    css: styles.css
    include-in-header: my-header-scripts.html
    include-after-body: my-footer-scripts.html